// This file is automatically generated. Update with your Supabase schema.
export type Database = {
  public: {
    Tables: {
      mascotas: {
        Row: {
          id: string;
          nombre: string;
          raza: string | null;
          caracteristicas: string | null;
          foto_url: string | null;
          qr_url: string;
          owner_id: string | null;
          owner_contact_encrypted: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          raza?: string | null;
          caracteristicas?: string | null;
          foto_url?: string | null;
          qr_url: string;
          owner_id?: string | null;
          owner_contact_encrypted: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          raza?: string | null;
          caracteristicas?: string | null;
          foto_url?: string | null;
          qr_url?: string;
          owner_id?: string | null;
          owner_contact_encrypted?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      mascotas_public: {
        Row: {
          id: string;
          nombre: string;
          raza: string | null;
          caracteristicas: string | null;
          foto_url: string | null;
          qr_url: string;
          owner_id: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      rescate_reports: {
        Row: {
          id: string;
          mascota_id: string;
          lat: number;
          lon: number;
          reporter_meta: Record<string, any> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          mascota_id: string;
          lat: number;
          lon: number;
          reporter_meta?: Record<string, any> | null;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          role: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};
